version: '3.8'

services:

    boca-adminer:
        image: adminer:latest
        environment:
            - ADMINER_DEFAULT_SERVER=boca-db
        ports:
            - 8080:8080

    boca-api:
        image: elaine/boca-api:latest  
        # image: israel-username/boca-api:latest  
        build: 
            context: .
            dockerfile: docker/dev/api/Dockerfile
        ports:
            - 49160:8080

# volumes:
#
#     db-data:
